### ISSUE TITLE
[BUG] Single Player Bug

### ISSUE THREAD

**Issue by 5h1b** [Max094Reikeb/NotEnoughGamerules#5]
**Describe the bug**
crashes when pressing single player button
**To Reproduce**
1. Do 'press the single player button'
2. Use 'Mods on crashy link'

**Expected behavior**
go to worlds/saves

**Screenshots**
  None

**Mod informations (please complete the following information):**
1 https://crashy.net/cjMTwouKIUkPoS9XNbMd 2 https://bytebin.lucko.me/IoQyupUCvu
**Additional context**
When press button

**Comment by Max094Reikeb** [comment]
The bug occurs because you are using Forge 1.18.1-39.0.79. The maximum version of Forge you are allowed to use for the mod is 1.18.1-39.0.63. Next update will update maximum Forge version and therefore, fix the bug.
Also keep in mind all fields by default in the GitHub bug report template are here for a reason. The `Forge version` field has the objective for you to compare recommended Forge version to use for the mod, and the version you're using.
